M48
; DRILL file {KiCad 7.0.1} date Sun Apr  2 16:08:43 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-02T16:08:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X-24.04Y20.195
X-24.04Y-20.195
X20.76Y20.195
X20.76Y-20.195
T0
M30
